# 应用名称, 默认: 程序名称
name:        "pgo2-demo"

# GO线程数, 默认: CPU核心数, 容器环境需要设置确定值
GOMAXPROCS:  4

# 运行时目录, 默认: "@app/runtime"
runtimePath: "@app/runtime"

# 静态资源目录, 默认: "@app/public"
# publicPath:  "@app/public"

# 视图模板目录, 默认: "@app/view"
# viewPath:    "@app/view"

server:
  # http服务地址, 若httpAddr与httpsAddr都为空, 则使用"0.0.0.0:8000"
  httpAddr:       "0.0.0.0:8000"

  # debug服务地址, /debug/pprof及状态输出, 默认为空
  # debugAddr:      "0.0.0.0:8100"

components:
  log:
    levels: "ALL"
    targets:
      info:
        name:     "file"
        levels:    "DEBUG,INFO,NOTICE"
        filePath:  "@runtime/notice.log"
      error:
        name:     "file"
        levels:    "WARN,ERROR,FATAL"
        filePath:  "@runtime/application.log"
